version: "3"

services:
  db:
    image: postgres:13-alpine3.15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data/pgdata
  api:
    build:
      context: backend
    volumes:
      - ./backend:/usr/src/app
      - ./backend/vendor/bundle:/usr/local/bundle
    ports:
      - "8080:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_HOST: db
      RAILS_MAX_THREADS: 5
      RAILS_ENV: development
  next:
    build:
      context: frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
